# SPDX-FileCopyrightText: 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

name: list_components_scheduled

on:
  schedule:
    - cron: '0 * * * *'

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17453/w_BaseKit_p_2021.1.0.2664.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17392/w_HPCKit_p_2021.1.0.2682.exe
  WINDOWS_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17406/w_IoTKit_p_2021.1.0.1220.exe
  WINDOWS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17405/w_RenderKit_p_2021.1.0.626.exe
  LINUX_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17431/l_BaseKit_p_2021.1.0.2659.sh
  LINUX_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17427/l_HPCKit_p_2021.1.0.2684.sh
  LINUX_IOTKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17420/l_IoTKit_p_2021.1.0.2658.sh
  LINUX_AIKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17421/l_AIKit_p_2021.1.0.935.sh
  LINUX_DLFDKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17399/l_DLFDKit_p_2021.1.0.1920.sh
  LINUX_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17448/l_RenderKit_p_2021.1.0.627.sh
  MACOS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17426/m_BaseKit_p_2021.1.0.2427.dmg
  MACOS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17398/m_HPCKit_p_2021.1.0.2681.dmg
  MACOS_RENDERKIT_URL: https://registrationcenter-download.intel.com/akdlm/irc_nas/17444/m_RenderKit_p_2021.1.0.626.dmg

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Intel® oneAPI Base Toolkit
      run: scripts/list_components_windows.bat $WINDOWS_BASEKIT_URL
    - name: Intel® oneAPI HPC Toolkit
      run: scripts/list_components_windows.bat $WINDOWS_HPCKIT_URL
    - name: Intel® oneAPI IoT Toolkit
      run: scripts/list_components_windows.bat $WINDOWS_IOTKIT_URL
    - name: Intel® oneAPI Rendering Toolkit
      run: scripts/list_components_windows.bat $WINDOWS_RENDERKIT_URL

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Intel® oneAPI Base Toolkit
      run: scripts/list_components_linux.sh $LINUX_BASEKIT_URL
    - name: Intel® oneAPI HPC Toolkit
      run: scripts/list_components_linux.sh $LINUX_HPCKIT_URL
    - name: Intel® oneAPI IoT Toolkit
      run: scripts/list_components_linux.sh $LINUX_IOTKIT_URL
    - name: Intel® AI Analytics Toolkit
      run: scripts/list_components_linux.sh $LINUX_AIKIT_URL
    - name: Intel® oneAPI DL Framework Developer Toolkit
      run: scripts/list_components_linux.sh $LINUX_DLFDKIT_URL
    - name: Intel® oneAPI Rendering Toolkit
      run: scripts/list_components_linux.sh $LINUX_RENDERKIT_URL

  linux_apt:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup yum/dnf repo
      run: scripts/setup_yum_dnf_repo_linux.sh
    - name: Intel® oneAPI packages provided in APT repository
      run: scripts/list_components_linux_apt.sh

  linux_yum_dnf:
    runs-on: ubuntu-latest
    container: fedora
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup yum/dnf repo
      run: scripts/setup_yum_dnf_repo_linux.sh
    - name: Intel® oneAPI packages provided in YUM/DNF repository
      run: scripts/list_components_linux_dnf.sh

  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Intel® oneAPI Base Toolkit
      run: scripts/list_components_macos.sh $MACOS_BASEKIT_URL
    - name: Intel® oneAPI HPC Toolkit
      run: scripts/list_components_macos.sh $MACOS_HPCKIT_URL
    - name: Intel® oneAPI Rendering Toolkit
      run: scripts/list_components_macos.sh $MACOS_RENDERKIT_URL
